[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_FIREBASE_API_KEY = "AIzaSyDjpryj-feHO_SiyCJXHTlEZcUV-nibyfA"
  VITE_FIREBASE_AUTH_DOMAIN = "smartdine1-81c82.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "smartdine1-81c82"
  VITE_FIREBASE_STORAGE_BUCKET = "smartdine1-81c82.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "732105111093"
  VITE_FIREBASE_APP_ID = "1:732105111093:web:1018e79194d3f0faa7637c"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
