export const DEMO_CATEGORIES = [
  {
    id: "starters",
    name: "Starters",
    description: "Appetizers & sizzling finger foods to kickstart your meal",
    imageUrl: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 1,
    createdAt: new Date().toISOString()
  },
  {
    id: "main-course",
    name: "Main Course",
    description: "Rich gravies, rich curries & aromatic royal breads",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 2,
    createdAt: new Date().toISOString()
  },
  {
    id: "biryani",
    name: "Biryani & Rice",
    description: "Fragrant dum-cooked basmati rice with exquisite spices",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 3,
    createdAt: new Date().toISOString()
  },
  {
    id: "pizza",
    name: "Pizza & Pastas",
    description: "Wood-fired artisanal pizzas & creamy Italian pastas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 4,
    createdAt: new Date().toISOString()
  },
  {
    id: "burgers",
    name: "Burgers & Wraps",
    description: "Juicy handcrafted burgers and crispy rolls",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: "south-indian",
    name: "South Indian",
    description: "Crispy dosas, fluffy idlis, and authentic chutneys",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 6,
    createdAt: new Date().toISOString()
  },
  {
    id: "chinese",
    name: "Chinese & Asian",
    description: "Wok-tossed noodles, spicy gravies, and dim sums",
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 7,
    createdAt: new Date().toISOString()
  },
  {
    id: "desserts",
    name: "Desserts & Bakes",
    description: "Irresistible sweet treats, pastries, and ice creams",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 8,
    createdAt: new Date().toISOString()
  },
  {
    id: "beverages",
    name: "Beverages & Shakes",
    description: "Chilled mocktails, thick shakes, lassis & hot coffees",
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80",
    active: true,
    displayOrder: 9,
    createdAt: new Date().toISOString()
  }
];

export const DEMO_MENU_ITEMS = [
  {
    id: "item-1",
    name: "Tandoori Paneer Tikka",
    description: "Chunks of fresh cottage cheese marinated in spiced yogurt and grilled to perfection in clay oven.",
    price: 280,
    categoryId: "starters",
    imageUrl: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15-20 min",
    rating: 4.8,
    ingredients: ["Paneer", "Yogurt", "Kashmiri Chilli", "Bell Peppers", "Onions", "Mint Chutney"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-2",
    name: "Murgh Malai Tikka",
    description: "Melt-in-mouth boneless chicken cubes marinated with heavy cream, cheese, cardamom, and herbs.",
    price: 360,
    categoryId: "starters",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    isVeg: false,
    available: true,
    popular: true,
    prepTime: "20-25 min",
    rating: 4.9,
    ingredients: ["Chicken", "Cream", "Cheese", "Green Cardamom", "Ginger Garlic", "Cashew paste"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-3",
    name: "Crispy Corn Pepper Salt",
    description: "Sweet American corn kernels tossed with crunchy peppers, scallions, and roasted Sichuan pepper.",
    price: 240,
    categoryId: "starters",
    imageUrl: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "12-15 min",
    rating: 4.5,
    ingredients: ["Sweet Corn", "Capsicum", "Spring Onion", "Black Pepper", "Garlic"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-4",
    name: "Paneer Butter Masala",
    description: "Cubes of tender paneer simmered in a luscious, mildly spiced tomato, butter, and cashew gravy.",
    price: 320,
    categoryId: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "20 min",
    rating: 4.9,
    ingredients: ["Paneer", "Fresh Tomatoes", "Cashews", "Butter", "Kasturi Methi", "Cream"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-5",
    name: "Butter Chicken (Murgh Makhani)",
    description: "Succulent shredded tandoori chicken cooked in an iconic velvety tomato and butter cream gravy.",
    price: 390,
    categoryId: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80",
    isVeg: false,
    available: true,
    popular: true,
    prepTime: "20-25 min",
    rating: 5.0,
    ingredients: ["Tandoori Chicken", "Tomatoes", "Butter", "Fresh Cream", "Honey", "Fenugreek"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-6",
    name: "Dal Makhani Grand",
    description: "Slow-cooked black lentils and kidney beans simmered overnight with butter, cream, and gentle spices.",
    price: 290,
    categoryId: "main-course",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.8,
    ingredients: ["Black Urad Dal", "Rajma", "White Butter", "Cream", "Garlic", "Tomatoes"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-7",
    name: "Hyderabadi Chicken Dum Biryani",
    description: "Long-grain basmati rice layered with spiced marinated chicken, saffron, and fried onions in sealed handi.",
    price: 380,
    categoryId: "biryani",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
    isVeg: false,
    available: true,
    popular: true,
    prepTime: "25 min",
    rating: 4.9,
    ingredients: ["Basmati Rice", "Chicken", "Saffron", "Mint", "Fried Onions (Birista)", "Ghee", "Raita"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-8",
    name: "Royal Veg Dum Biryani",
    description: "Fresh garden vegetables, paneer, and aromatic spices slow-cooked with basmati rice and saffron.",
    price: 310,
    categoryId: "biryani",
    imageUrl: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "20 min",
    rating: 4.7,
    ingredients: ["Basmati Rice", "Paneer", "Carrots", "Beans", "Peas", "Kesar", "Mint", "Raita"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-9",
    name: "Margherita Basilico Pizza",
    description: "Classic Italian thin crust topped with San Marzano tomato sauce, fresh mozzarella, and aromatic basil leaves.",
    price: 340,
    categoryId: "pizza",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "18-20 min",
    rating: 4.7,
    ingredients: ["Hand-stretched Dough", "San Marzano Sauce", "Fresh Mozzarella", "Extra Virgin Olive Oil", "Basil"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-10",
    name: "Smoked Chicken BBQ Pizza",
    description: "Loaded with shredded BBQ chicken, roasted onions, bell peppers, jalapeños, and mozzarella blend.",
    price: 440,
    categoryId: "pizza",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    isVeg: false,
    available: true,
    popular: true,
    prepTime: "20 min",
    rating: 4.9,
    ingredients: ["Smoked Chicken", "Hickory BBQ Sauce", "Jalapenos", "Mozzarella", "Cheddar", "Red Onion"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-11",
    name: "Crispy Peri-Peri Veg Burger",
    description: "Crunchy herb potato patty dusted with spicy African peri-peri seasoning, lettuce, cheese, and chipotle mayo.",
    price: 210,
    categoryId: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "15 min",
    rating: 4.6,
    ingredients: ["Brioche Bun", "Crispy Veg Patty", "Peri Peri Dust", "Cheese Slice", "Lettuce", "Chipotle Dip"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-12",
    name: "Double Gourmet Smash Burger",
    description: "Twin juicy grilled chicken patties with melted aged cheddar, caramelized onions, and house secret sauce.",
    price: 330,
    categoryId: "burgers",
    imageUrl: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
    isVeg: false,
    available: true,
    popular: true,
    prepTime: "18 min",
    rating: 4.8,
    ingredients: ["Toasted Brioche", "Double Chicken Patty", "Double Cheddar", "Caramelized Onions", "Pickles"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-13",
    name: "Crispy Ghee Podi Masala Dosa",
    description: "Golden crispy crepe roasted in pure cow ghee, smeared with spicy gunpowder podi and filled with potato masala.",
    price: 190,
    categoryId: "south-indian",
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12 min",
    rating: 4.9,
    ingredients: ["Fermented Batter", "Desi Ghee", "Spicy Podi", "Spiced Potato Masala", "Coconut Chutney", "Sambar"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-14",
    name: "Steamed Button Idlis with Vada Combo",
    description: "Mini pillowy steamed rice cakes and a crispy medu vada served with piping hot authentic drumstick sambar.",
    price: 160,
    categoryId: "south-indian",
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "10 min",
    rating: 4.7,
    ingredients: ["Steamed Idlis", "Crispy Urad Vada", "Drumstick Sambar", "Tomato Chutney", "Coconut Chutney"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-15",
    name: "Veg Manchurian Dry / Gravy",
    description: "Crispy vegetable balls tossed in an umami ginger, garlic, dark soya sauce, and spring onion glaze.",
    price: 250,
    categoryId: "chinese",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.6,
    ingredients: ["Cabbage", "Carrot", "Spring Onions", "Ginger Garlic", "Dark Soya", "Chilli Paste"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-16",
    name: "Chilli Garlic Hakka Noodles",
    description: "Wok-tossed noodles with colorful julienned bell peppers, shredded cabbage, burnt garlic, and red chillies.",
    price: 230,
    categoryId: "chinese",
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "15 min",
    rating: 4.7,
    ingredients: ["Hakka Noodles", "Burnt Garlic", "Red Chilli Flakes", "Bell Peppers", "Soy Sauce", "Sesame"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-17",
    name: "Sizzling Chocolate Walnut Brownie",
    description: "Warm fudgy dark chocolate brownie served on a smoking sizzler plate topped with vanilla bean ice cream and hot fudge.",
    price: 220,
    categoryId: "desserts",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.9,
    ingredients: ["Belgian Dark Chocolate", "Toasted Walnuts", "Vanilla Bean Gelato", "Hot Chocolate Fudge"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-18",
    name: "Shahi Gulab Jamun with Rabdi",
    description: "Golden fried milk-solid dumplings soaked in rose and saffron cardamom sugar syrup, paired with thick rabdi.",
    price: 180,
    categoryId: "desserts",
    imageUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "8 min",
    rating: 4.8,
    ingredients: ["Khoya (Mawa)", "Rose Water", "Cardamom", "Saffron Rabdi", "Pistachio flakes"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-19",
    name: "Classic Alphonso Mango Lassi",
    description: "Traditional thick yogurt smoothie blended with sweet Ratnagiri Alphonso mango pulp and cardamom.",
    price: 150,
    categoryId: "beverages",
    imageUrl: "https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.9,
    ingredients: ["Fresh Curd", "Alphonso Mango Pulp", "Cardamom", "Saffron Strands", "Crushed Pistachios"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-20",
    name: "Signature Cold Coffee Frappe",
    description: "Freshly brewed espresso blended with rich vanilla ice cream, chilled milk, and drizzled with chocolate ganache.",
    price: 170,
    categoryId: "beverages",
    imageUrl: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "6 min",
    rating: 4.8,
    ingredients: ["Arabica Espresso", "Whole Milk", "Vanilla Ice Cream", "Chocolate Ganache", "Whipped Cream"],
    createdAt: new Date().toISOString()
  },
  {
    id: "item-21",
    name: "Crispy Peri-Peri French Fries",
    description: "Golden crispy skin-on potato fries tossed in hot & zesty peri-peri spice blend served with garlic aioli.",
    price: 160,
    categoryId: "starters",
    imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80",
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.7,
    ingredients: ["Potatoes", "Peri Peri Seasoning", "Sea Salt", "Garlic Aioli Dip"],
    createdAt: new Date().toISOString()
  }
];

export const DEMO_TABLES = [
  { id: "table-1", tableNumber: "01", capacity: 2, active: true, location: "Window Side", qrUrl: "https://smartdine.netlify.app/menu?table=01", deepLink: "smartdine://table/01" },
  { id: "table-2", tableNumber: "02", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=02", deepLink: "smartdine://table/02" },
  { id: "table-3", tableNumber: "03", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=03", deepLink: "smartdine://table/03" },
  { id: "table-4", tableNumber: "04", capacity: 6, active: true, location: "Family Booth", qrUrl: "https://smartdine.netlify.app/menu?table=04", deepLink: "smartdine://table/04" },
  { id: "table-5", tableNumber: "05", capacity: 2, active: true, location: "Terrace Balcony", qrUrl: "https://smartdine.netlify.app/menu?table=05", deepLink: "smartdine://table/05" },
  { id: "table-6", tableNumber: "06", capacity: 4, active: true, location: "Terrace Balcony", qrUrl: "https://smartdine.netlify.app/menu?table=06", deepLink: "smartdine://table/06" },
  { id: "table-7", tableNumber: "07", capacity: 8, active: true, location: "VIP Lounge", qrUrl: "https://smartdine.netlify.app/menu?table=07", deepLink: "smartdine://table/07" },
  { id: "table-8", tableNumber: "08", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=08", deepLink: "smartdine://table/08" },
  { id: "table-9", tableNumber: "09", capacity: 2, active: true, location: "Garden Courtyard", qrUrl: "https://smartdine.netlify.app/menu?table=09", deepLink: "smartdine://table/09" },
  { id: "table-10", tableNumber: "10", capacity: 6, active: true, location: "Garden Courtyard", qrUrl: "https://smartdine.netlify.app/menu?table=10", deepLink: "smartdine://table/10" }
];

export const DEMO_ORDERS = [
  {
    id: "ORD-9821",
    tableNumber: "02",
    customerName: "Rahul Sharma",
    customerPhone: "+91 98765 43210",
    customerId: "cust-1",
    items: [
      { itemId: "item-1", name: "Tandoori Paneer Tikka", price: 280, quantity: 1, isVeg: true },
      { itemId: "item-4", name: "Paneer Butter Masala", price: 320, quantity: 1, isVeg: true },
      { itemId: "item-19", name: "Classic Alphonso Mango Lassi", price: 150, quantity: 2, isVeg: true }
    ],
    subtotal: 900,
    tax: 45,
    total: 945,
    status: "preparing",
    paymentStatus: "paid",
    paymentMethod: "UPI / Counter",
    notes: "Make it medium spicy please",
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString()
  },
  {
    id: "ORD-9822",
    tableNumber: "05",
    customerName: "Priya Nair",
    customerPhone: "+91 91234 56789",
    customerId: "cust-2",
    items: [
      { itemId: "item-7", name: "Hyderabadi Chicken Dum Biryani", price: 380, quantity: 2, isVeg: false },
      { itemId: "item-17", name: "Sizzling Chocolate Walnut Brownie", price: 220, quantity: 1, isVeg: true }
    ],
    subtotal: 980,
    tax: 49,
    total: 1029,
    status: "accepted",
    paymentStatus: "pending",
    paymentMethod: "Pay after Dining",
    notes: "Extra raita",
    createdAt: new Date(Date.now() - 6 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString()
  },
  {
    id: "ORD-9823",
    tableNumber: "01",
    customerName: "Guest (Table 01)",
    customerPhone: "+91 99887 76655",
    customerId: null,
    items: [
      { itemId: "item-9", name: "Margherita Basilico Pizza", price: 340, quantity: 1, isVeg: true },
      { itemId: "item-20", name: "Signature Cold Coffee Frappe", price: 170, quantity: 1, isVeg: true }
    ],
    subtotal: 510,
    tax: 25.5,
    total: 535.5,
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "Pay at Counter",
    notes: "Crispy crust",
    createdAt: new Date(Date.now() - 1 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString()
  }
];
