export const DEMO_CATEGORIES = [
  {
    id: "special-thalis",
    name: "⭐ Special Thalis",
    description: "Wholesome royal regional Indian thalis served with authentic curries, breads & sweets",
    imageUrl: "/dishes/gujarati_thali.jpg",
    active: true,
    displayOrder: 1,
    createdAt: new Date().toISOString()
  },
  {
    id: "marathi",
    name: "Marathi",
    description: "Authentic Maharashtrian specialties, spicy curries & traditional snacks",
    imageUrl: "/dishes/vada_pav.jpg",
    active: true,
    displayOrder: 2,
    createdAt: new Date().toISOString()
  },
  {
    id: "south-indian",
    name: "South Indian",
    description: "Crispy dosas, fluffy idlis, vada & authentic South Indian chutneys",
    imageUrl: "/dishes/vegetable_uttapam.jpg",
    active: true,
    displayOrder: 3,
    createdAt: new Date().toISOString()
  },
  {
    id: "punjabi",
    name: "Punjabi",
    description: "Rich buttery gravies, spicy chole, dal makhani & tandoori kulchas",
    imageUrl: "/dishes/chole_bhature.jpg",
    active: true,
    displayOrder: 4,
    createdAt: new Date().toISOString()
  },
  {
    id: "gujarati",
    name: "Gujarati",
    description: "Traditional Gujarati thali, dhokla, thepla & wholesome regional food",
    imageUrl: "/dishes/gujarati_thali.jpg",
    active: true,
    displayOrder: 5,
    createdAt: new Date().toISOString()
  },
  {
    id: "north-indian",
    name: "North Indian",
    description: "Royal paneer gravies, kadai spices, creamy curries & tandoori naans",
    imageUrl: "/dishes/shahi_paneer.jpg",
    active: true,
    displayOrder: 6,
    createdAt: new Date().toISOString()
  },
  {
    id: "indo-chinese",
    name: "Indo-Chinese",
    description: "Wok-tossed noodles, manchurian balls, chilli paneer & crispy spring rolls",
    imageUrl: "/dishes/veg_hakka_noodles.jpg",
    active: true,
    displayOrder: 7,
    createdAt: new Date().toISOString()
  },
  {
    id: "fast-food",
    name: "Fast Food & Snacks",
    description: "Handcrafted burgers, cheesy pizzas, samosas, sandwiches & pav bhaji",
    imageUrl: "/dishes/veg_pizza.jpg",
    active: true,
    displayOrder: 8,
    createdAt: new Date().toISOString()
  },
  {
    id: "desserts",
    name: "Desserts",
    description: "Hot gulab jamun, creamy rasmalai, gajar halwa, kulfi & jalebi",
    imageUrl: "/dishes/gulab_jamun.jpg",
    active: true,
    displayOrder: 9,
    createdAt: new Date().toISOString()
  },
  {
    id: "beverages",
    name: "Beverages",
    description: "Masala chai, thick mango lassis, frappes, fresh lime & spiced buttermilk",
    imageUrl: "/dishes/masala_chai.jpg",
    active: true,
    displayOrder: 10,
    createdAt: new Date().toISOString()
  }
];

export const DEMO_MENU_ITEMS = [
  // ==========================================
  // 1. MARATHI CUISINE (1 - 6)
  // ==========================================
  {
    id: "item-1",
    name: "Misal Pav",
    category: "Marathi",
    categoryId: "marathi",
    description: "Spicy Maharashtrian sprouted curry topped with farsan, onion, coriander and lemon, served with soft pav.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-12 min",
    rating: 4.9,
    ingredients: ["Sprouted Moth Beans", "Spicy Kat/Rassa", "Crispy Farsan", "Chopped Onions", "Lemon", "Buttered Pav"],
    imageUrl: "/dishes/misal_pav.jpg",
    imagePrompt: "Ultra-realistic authentic Maharashtrian Misal Pav, a traditional spicy misal curry made with sprouted moth beans and peas in a rich red spicy gravy, generously topped with crispy farsan, finely chopped red onion, fresh coriander and a small lemon wedge, served with two soft golden pav buns on the side, traditional Maharashtrian restaurant-style presentation, curry served in an elegant dark ceramic bowl, pav placed neatly beside it, appetizing freshly prepared food, realistic ingredients and textures, visible oil and spice details, natural steam, premium professional food photography, DSLR quality, sharp focus, high dynamic range, soft warm studio lighting, realistic shadows, shallow depth of field, clean wooden restaurant table background, authentic Indian food styling, photorealistic, ultra-detailed, 8K UHD, 1:1 square composition, no people, no hands, no text, no writing, no logo, no watermark, no artificial-looking food.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-2",
    name: "Vada Pav",
    category: "Marathi",
    categoryId: "marathi",
    description: "Mumbai-style crispy potato vada inside soft pav with chutneys.",
    price: 60,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5-8 min",
    rating: 4.8,
    ingredients: ["Batata Vada", "Pav Bun", "Garlic Red Chutney", "Green Mint Chutney", "Fried Chili"],
    imageUrl: "/dishes/vada_pav.jpg",
    imagePrompt: "Ultra-realistic Mumbai-style Vada Pav, crispy golden potato vada inside soft fresh pav, green chutney and red garlic chutney, fried green chili on side, authentic Indian street-food restaurant presentation, realistic crispy texture, premium food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-3",
    name: "Puran Poli",
    category: "Marathi",
    categoryId: "marathi",
    description: "Traditional Maharashtrian sweet flatbread stuffed with jaggery and chana dal, served with ghee.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-15 min",
    rating: 4.9,
    ingredients: ["Wheat Flour", "Chana Dal", "Organic Jaggery", "Nutmeg", "Cardamom", "Pure Desi Ghee"],
    imageUrl: "/dishes/puran_poli.jpg",
    imagePrompt: "Ultra-realistic traditional Maharashtrian Puran Poli, soft golden sweet flatbread filled with jaggery and chana dal, served with melted ghee in a small bowl, authentic Maharashtrian restaurant presentation, realistic flaky texture, warm golden lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-4",
    name: "Sabudana Khichdi",
    category: "Marathi",
    categoryId: "marathi",
    description: "Tapioca pearls cooked with roasted peanuts, potatoes, cumin and green chilies.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "8-10 min",
    rating: 4.7,
    ingredients: ["Tapioca Pearls", "Crushed Peanuts", "Diced Potatoes", "Cumin", "Green Chilies", "Lemon Juice"],
    imageUrl: "/dishes/sabudana_khichdi.jpg",
    imagePrompt: "Ultra-realistic Maharashtrian Sabudana Khichdi, translucent tapioca pearls mixed with roasted peanuts, potatoes, cumin, green chili and coriander, lemon wedge on side, served in elegant bowl, authentic Indian restaurant photography, realistic texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-5",
    name: "Kothimbir Vadi",
    category: "Marathi",
    categoryId: "marathi",
    description: "Crispy coriander and gram flour Maharashtrian snack served with chutney.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.8,
    ingredients: ["Fresh Coriander", "Besan (Gram Flour)", "Sesame Seeds", "Ginger Garlic", "Spices"],
    imageUrl: "/dishes/kothimbir_vadi.jpg",
    imagePrompt: "Ultra-realistic Maharashtrian Kothimbir Vadi, crispy golden coriander and gram flour snack pieces cut into squares, served with fresh green chutney and fried green chili, authentic Maharashtrian restaurant plating, realistic crispy texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-6",
    name: "Thalipeeth",
    category: "Marathi",
    categoryId: "marathi",
    description: "Multigrain Maharashtrian flatbread made with spices and coriander, served with yogurt and chutney.",
    price: 110,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "12 min",
    rating: 4.7,
    ingredients: ["Bhajani Multigrain Flour", "Onions", "Coriander", "Cumin", "White Butter (Loni)", "Fresh Curd"],
    imageUrl: "/dishes/thalipeeth.jpg",
    imagePrompt: "Ultra-realistic Maharashtrian Thalipeeth, crispy golden multigrain flatbread containing coriander, onion and traditional spices, served with fresh yogurt, green chutney and homemade pickle, authentic restaurant presentation, realistic crispy texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 2. SOUTH INDIAN CUISINE (7 - 12)
  // ==========================================
  {
    id: "item-7",
    name: "Masala Dosa",
    category: "South Indian",
    categoryId: "south-indian",
    description: "Crispy golden dosa filled with spiced potato masala, served with sambar and coconut chutney.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-12 min",
    rating: 5.0,
    ingredients: ["Crispy Rice Crepe", "Spiced Potato Masala", "Lentil Sambar", "Fresh Coconut Chutney", "Tomato Chutney"],
    imageUrl: "/dishes/masala_dosa.jpg",
    imagePrompt: "Ultra-realistic authentic South Indian Masala Dosa, large thin paper-crisp golden dosa rolled and filled with fragrant spiced potato masala, served on a banana leaf platter with hot lentil sambar, white coconut chutney and tomato chutney, professional food photography, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-8",
    name: "Idli Sambar",
    category: "South Indian",
    categoryId: "south-indian",
    description: "Soft steamed idlis served with hot sambar and coconut chutney.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "6-8 min",
    rating: 4.8,
    ingredients: ["Steamed Rice Idlis", "Drumstick Sambar", "Coconut Chutney", "Curry Leaves"],
    imageUrl: "/dishes/idli_sambar.jpg",
    imagePrompt: "Ultra-realistic South Indian Idli Sambar, four soft fluffy white idlis arranged on a traditional stainless steel plate, bowl of hot sambar and coconut chutney on side, fresh coriander garnish, visible steam, authentic restaurant presentation, realistic texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-9",
    name: "Medu Vada",
    category: "South Indian",
    categoryId: "south-indian",
    description: "Crispy South Indian lentil fritters served with sambar and coconut chutney.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "8-10 min",
    rating: 4.8,
    ingredients: ["Black Lentil Vada", "Black Pepper", "Curry Leaves", "Sambar", "Coconut Chutney"],
    imageUrl: "/dishes/medu_vada.jpg",
    imagePrompt: "Ultra-realistic South Indian Medu Vada, crispy golden ring-shaped lentil fritters with fluffy soft interior, served with hot sambar and coconut chutney, traditional stainless steel restaurant plate, realistic crispy texture, premium food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-10",
    name: "Vegetable Uttapam",
    category: "South Indian",
    categoryId: "south-indian",
    description: "Thick soft South Indian pancake topped with onion, tomato, capsicum and coriander.",
    price: 110,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "10-12 min",
    rating: 4.7,
    ingredients: ["Fermented Batter", "Onions", "Tomatoes", "Capsicum", "Coriander", "Sambar"],
    imageUrl: "/dishes/vegetable_uttapam.jpg",
    imagePrompt: "Ultra-realistic authentic South Indian Vegetable Uttapam, thick soft golden uttapam topped with finely chopped tomato, onion, capsicum, coriander and green chili, served with coconut chutney and sambar in traditional stainless steel bowls, premium restaurant plating, appetizing fresh texture, warm natural studio lighting, shallow depth of field, photorealistic, 8K UHD, 1:1 square composition, clean background, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-11",
    name: "Ven Pongal",
    category: "South Indian",
    categoryId: "south-indian",
    description: "Traditional rice and moong dal dish flavored with ghee, black pepper and cumin.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "8-10 min",
    rating: 4.8,
    ingredients: ["Rice", "Moong Dal", "Pure Ghee", "Whole Pepper", "Cumin", "Cashews", "Curry Leaves"],
    imageUrl: "/dishes/ven_pongal.jpg",
    imagePrompt: "Ultra-realistic traditional South Indian Ven Pongal, creamy rice and moong dal cooked with ghee, black pepper, cumin and cashews, served hot in a premium ceramic bowl with coconut chutney and sambar on the side, visible steam, authentic restaurant presentation, realistic food texture, cinematic soft lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-12",
    name: "Lemon Rice",
    category: "South Indian",
    categoryId: "south-indian",
    description: "South Indian rice flavored with lemon, curry leaves, mustard seeds and peanuts.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "8 min",
    rating: 4.6,
    ingredients: ["Basmati Rice", "Fresh Lemon Juice", "Turmeric", "Mustard Seeds", "Peanuts", "Curry Leaves"],
    imageUrl: "/dishes/lemon_rice.jpg",
    imagePrompt: "Ultra-realistic South Indian Lemon Rice, fluffy yellow basmati rice flavored with fresh lemon, mustard seeds, curry leaves, roasted peanuts and green chili, served in an elegant ceramic bowl with lemon slice and coriander garnish, premium Indian restaurant photography, realistic rice texture, soft studio lighting, 8K UHD, 1:1 square composition, clean background, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 3. PUNJABI CUISINE (13 - 18)
  // ==========================================
  {
    id: "item-13",
    name: "Paneer Butter Masala",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Soft paneer cubes cooked in rich creamy tomato and butter gravy.",
    price: 180,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15-18 min",
    rating: 4.9,
    ingredients: ["Fresh Paneer", "Tomato Puree", "Cashew Paste", "Butter", "Fresh Cream", "Kasuri Methi"],
    imageUrl: "/dishes/paneer_butter_masala.jpg",
    imagePrompt: "Ultra-realistic North Indian Paneer Butter Masala, tender cubes of fresh cottage cheese swimming in velvety smooth orange-red makhani gravy, drizzled with fresh white cream swirl, melting cube of butter, and crushed aromatic fenugreek leaves, served in a copper handi, soft studio lighting, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-14",
    name: "Chole Bhature",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Spicy Punjabi chickpea curry served with fluffy golden bhatura.",
    price: 150,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-12 min",
    rating: 5.0,
    ingredients: ["Kabuli Chana", "Pindi Chole Masala", "Fluffy Bhature", "Pickled Onions", "Green Chutney"],
    imageUrl: "/dishes/chole_bhature.jpg",
    imagePrompt: "Ultra-realistic Punjabi Chole Bhature, two large fluffy golden bhaturas with a bowl of spicy chickpea chole, sliced onion, green chili, coriander and lemon, premium Indian restaurant presentation, crispy detailed texture, warm appetizing lighting, professional food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-15",
    name: "Dal Makhani",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Slow-cooked black lentils and kidney beans in a creamy buttery gravy.",
    price: 160,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12-15 min",
    rating: 4.9,
    ingredients: ["Black Urad Dal", "Rajma", "White Butter", "Cream", "Garlic Tomato Base", "Kasuri Methi"],
    imageUrl: "/dishes/dal_makhani.jpg",
    imagePrompt: "Ultra-realistic Punjabi Dal Makhani, rich creamy black lentils and kidney beans slow-cooked with butter and aromatic spices, topped with a small butter swirl and coriander, served in a black premium ceramic bowl with naan in background, restaurant menu photography, highly detailed realistic texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-16",
    name: "Amritsari Kulcha",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Crispy stuffed Punjabi kulcha served with spicy chole and onion.",
    price: 150,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12-15 min",
    rating: 4.8,
    ingredients: ["Flour Dough", "Spiced Potato Mash", "Anardana", "Desi Ghee", "Chole", "Onion Salad"],
    imageUrl: "/dishes/amritsari_kulcha.jpg",
    imagePrompt: "Ultra-realistic Amritsari Kulcha, crispy golden stuffed Punjabi kulcha with visible potato and spice filling, topped with butter and coriander, served with spicy chole, onion rings and chutney, traditional Punjabi restaurant plating, realistic charred edges and texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-17",
    name: "Rajma Chawal",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Punjabi kidney bean curry served with steamed basmati rice.",
    price: 140,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.8,
    ingredients: ["Red Kidney Beans", "Thick Onion Tomato Gravy", "Spices", "Basmati Rice", "Desi Ghee", "Pickle"],
    imageUrl: "/dishes/rajma_chawal.jpg",
    imagePrompt: "Ultra-realistic Punjabi Rajma Chawal, thick red kidney bean curry in rich tomato gravy served beside fluffy steamed basmati rice, coriander garnish, onion and lemon on side, premium Indian restaurant plating, realistic food texture, soft natural lighting, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-18",
    name: "Aloo Paratha",
    category: "Punjabi",
    categoryId: "punjabi",
    description: "Golden stuffed potato paratha served with yogurt, butter and pickle.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-12 min",
    rating: 4.8,
    ingredients: ["Wheat Flatbread", "Spiced Potatoes", "Green Chilies", "Coriander", "White Butter", "Curd", "Pickle"],
    imageUrl: "/dishes/aloo_paratha.jpg",
    imagePrompt: "Ultra-realistic Punjabi Aloo Paratha, golden crispy stuffed potato flatbread with visible flaky layers, served with a cube of butter, bowl of yogurt, pickle and green chutney, rustic premium Indian restaurant setting, realistic texture, warm studio lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 4. GUJARATI CUISINE (19 - 24)
  // ==========================================
  {
    id: "item-19",
    name: "Gujarati Thali",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Complete Gujarati meal containing dal, kadhi, sabzi, roti, rice, dhokla, farsan, pickle, papad and sweet.",
    price: 250,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12-15 min",
    rating: 5.0,
    ingredients: ["Gujarati Dal", "Kadhi", "Shaak Sabzi", "Rotli with Ghee", "Rice", "Dhokla", "Papad", "Shrikhand"],
    imageUrl: "/dishes/gujarati_thali.jpg",
    imagePrompt: "Ultra-realistic authentic Gujarati Thali, large traditional stainless steel thali containing dal, Gujarati kadhi, vegetable sabzi, rotli, rice, dhokla, farsan, pickle, papad, salad and Indian sweet, beautifully arranged compartments, premium Gujarati restaurant presentation, highly detailed realistic food textures, 8K UHD, overhead 1:1 composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-20",
    name: "Khaman Dhokla",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Soft steamed Gujarati gram flour snack topped with mustard seeds and coriander.",
    price: 80,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "6-8 min",
    rating: 4.8,
    ingredients: ["Gram Flour (Besan)", "Mustard Seeds", "Sesame Seeds", "Green Chilies", "Coriander", "Coconut"],
    imageUrl: "/dishes/khaman_dhokla.jpg",
    imagePrompt: "Ultra-realistic Gujarati Khaman Dhokla, soft fluffy bright-yellow steamed gram flour cubes topped with mustard seeds, sesame, curry leaves and fresh coriander, served with green chutney, premium Gujarati restaurant presentation, realistic porous texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-21",
    name: "Methi Thepla",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Gujarati flatbread flavored with fresh fenugreek leaves and spices, served with yogurt and pickle.",
    price: 80,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "8-10 min",
    rating: 4.7,
    ingredients: ["Wheat Flour", "Fresh Fenugreek (Methi)", "Turmeric", "Carom Seeds", "Sesame", "Yogurt Dip", "Chhundo"],
    imageUrl: "/dishes/methi_thepla.jpg",
    imagePrompt: "Ultra-realistic Gujarati Methi Thepla, stack of golden-brown fenugreek flatbreads with visible methi leaves and spices, served with fresh yogurt, pickle and green chutney, authentic Gujarati restaurant plating, realistic texture, warm natural lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-22",
    name: "Fafda Jalebi",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Crispy fafda served with sweet orange jalebi and green chutney.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "6-8 min",
    rating: 4.9,
    ingredients: ["Crispy Gram Flour Fafda", "Carom Seeds", "Crisp Jalebi", "Papaya Sambharo", "Fried Green Chili"],
    imageUrl: "/dishes/fafda_jalebi.jpg",
    imagePrompt: "Ultra-realistic Gujarati Fafda Jalebi, crispy thin golden fafda arranged beside bright orange spiral jalebi, green chutney and fried green chili, authentic Gujarati street-food presentation, highly detailed crispy texture, appetizing warm lighting, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-23",
    name: "Handvo",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Savory Gujarati baked lentil and rice cake with a crispy sesame crust.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "12 min",
    rating: 4.7,
    ingredients: ["Lentil Rice Batter", "Bottle Gourd", "Mustard Seeds", "Sesame Seeds", "Curry Leaves", "Green Chilies"],
    imageUrl: "/dishes/handvo.jpg",
    imagePrompt: "Ultra-realistic Gujarati Handvo, thick savory lentil and rice cake with golden crispy sesame crust, sliced into triangular pieces, served with green chutney and yogurt, traditional Gujarati restaurant presentation, realistic baked texture, premium food photography, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-24",
    name: "Gujarati Kadhi",
    category: "Gujarati",
    categoryId: "gujarati",
    description: "Mild yogurt-based Gujarati curry flavored with spices and curry leaves.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "8 min",
    rating: 4.6,
    ingredients: ["Whisked Yogurt", "Besan", "Ginger Green Chili", "Cinnamon", "Cloves", "Mustard Seeds", "Curry Leaves", "Jaggery"],
    imageUrl: "/dishes/gujarati_kadhi.jpg",
    imagePrompt: "Ultra-realistic Gujarati Kadhi, smooth creamy yellow yogurt-based curry with mustard seeds, curry leaves, coriander and mild spices, served in a traditional ceramic bowl with steamed rice in background, premium Indian restaurant photography, realistic texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 5. NORTH INDIAN CUISINE (25 - 31)
  // ==========================================
  {
    id: "item-25",
    name: "Shahi Paneer",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Paneer cooked in rich creamy tomato and cashew gravy.",
    price: 180,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.9,
    ingredients: ["Paneer Triangles", "Cashew Nut Paste", "Melon Seeds", "Tomato Puree", "Cardamom", "Fresh Cream"],
    imageUrl: "/dishes/shahi_paneer.jpg",
    imagePrompt: "Ultra-realistic North Indian Shahi Paneer, soft paneer cubes in rich creamy orange tomato-cashew gravy, cream swirl, saffron and coriander garnish, served in premium black bowl with naan in background, luxurious restaurant menu photography, realistic texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-26",
    name: "Kadai Paneer",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Paneer cooked with bell peppers, onions and aromatic kadai spices.",
    price: 180,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.8,
    ingredients: ["Paneer Cubes", "Green Bell Peppers", "Red Onions", "Kadai Spices", "Tomato Gravy"],
    imageUrl: "/dishes/kadai_paneer.jpg",
    imagePrompt: "Ultra-realistic Kadai Paneer, chunky paneer cubes cooked with colorful bell peppers, onions, tomatoes and aromatic crushed coriander spices, served in traditional iron kadai, fresh coriander garnish, premium Indian restaurant photography, realistic charred texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-27",
    name: "Palak Paneer",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Soft paneer cubes cooked in creamy spinach gravy.",
    price: 170,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12-15 min",
    rating: 4.8,
    ingredients: ["Spinach Puree (Palak)", "Paneer Cubes", "Garlic", "Ginger", "Fresh Cream", "Garam Masala"],
    imageUrl: "/dishes/palak_paneer.jpg",
    imagePrompt: "Ultra-realistic Palak Paneer, soft paneer cubes in rich creamy green spinach gravy, cream swirl and coriander garnish, served in elegant black ceramic bowl, premium North Indian restaurant presentation, realistic spinach and paneer texture, soft studio lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-28",
    name: "Chana Masala",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Spicy chickpeas cooked in onion and tomato gravy.",
    price: 130,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "10-12 min",
    rating: 4.7,
    ingredients: ["White Chickpeas", "Onion Tomato Gravy", "Coriander", "Amchur", "Ginger Juliennes"],
    imageUrl: "/dishes/chana_masala.jpg",
    imagePrompt: "Ultra-realistic North Indian Chana Masala, spicy chickpeas cooked in thick tomato-onion gravy, garnished with coriander, ginger strips and lemon, served in traditional bowl with naan in background, restaurant-quality food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-29",
    name: "Mix Veg Curry",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Mixed seasonal vegetables cooked in aromatic Indian gravy.",
    price: 150,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "12-15 min",
    rating: 4.6,
    ingredients: ["Carrots", "Beans", "Green Peas", "Cauliflower", "Paneer", "Rich Onion Cashew Sauce"],
    imageUrl: "/dishes/mix_veg_curry.jpg",
    imagePrompt: "Ultra-realistic North Indian Mix Vegetable Curry containing carrots, peas, cauliflower, beans, capsicum and potatoes in rich aromatic Indian gravy, coriander garnish, premium restaurant bowl, realistic vegetable texture, professional food photography, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-30",
    name: "Butter Naan",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Soft tandoori naan brushed with butter.",
    price: 60,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.9,
    ingredients: ["Wheat Flour", "Yogurt Dough", "Tandoor Baked", "Amul Butter"],
    imageUrl: "/dishes/butter_naan.jpg",
    imagePrompt: "Ultra-realistic freshly baked Butter Naan, soft golden tandoori naan with blistered charred spots, brushed with melted butter and coriander, served on a premium wooden restaurant table with curry bowl in background, realistic bread texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-31",
    name: "Garlic Naan",
    category: "North Indian",
    categoryId: "north-indian",
    description: "Tandoori naan topped with fresh garlic and coriander.",
    price: 70,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 5.0,
    ingredients: ["Leavened Flour", "Minced Garlic", "Fresh Coriander", "Black Sesame", "Butter"],
    imageUrl: "/dishes/garlic_naan.jpg",
    imagePrompt: "Ultra-realistic Garlic Naan, freshly baked soft tandoori naan covered with chopped garlic, coriander and butter, visible charred spots, served with Indian curry in background, premium restaurant menu photography, realistic texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 6. INDO-CHINESE CUISINE (32 - 36)
  // ==========================================
  {
    id: "item-32",
    name: "Veg Hakka Noodles",
    category: "Indo-Chinese",
    categoryId: "indo-chinese",
    description: "Stir-fried noodles with cabbage, carrot, capsicum and spring onion.",
    price: 140,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.8,
    ingredients: ["Wheat Noodles", "Shredded Cabbage", "Carrots", "Bell Peppers", "Spring Onions", "Soy Sauce"],
    imageUrl: "/dishes/veg_hakka_noodles.jpg",
    imagePrompt: "Ultra-realistic Indo-Chinese Veg Hakka Noodles, thin glossy stir-fried noodles tossed in high heat wok with crunchy julienned colorful vegetables like purple cabbage, carrots, bell peppers, and scallions in a modern black ceramic bowl, soft studio lighting, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-33",
    name: "Veg Manchurian",
    category: "Indo-Chinese",
    categoryId: "indo-chinese",
    description: "Crispy vegetable balls coated in spicy Indo-Chinese sauce.",
    price: 150,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12 min",
    rating: 4.8,
    ingredients: ["Vegetable Fritters", "Ginger Garlic Sauce", "Dark Soy Sauce", "Chili Glaze", "Spring Onions"],
    imageUrl: "/dishes/veg_manchurian.jpg",
    imagePrompt: "Ultra-realistic Indo-Chinese Vegetable Manchurian, crispy golden vegetable balls coated in glossy spicy Manchurian sauce, spring onion and sesame garnish, served in elegant black bowl, premium restaurant food photography, realistic sauce texture, dramatic soft lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-34",
    name: "Veg Fried Rice",
    category: "Indo-Chinese",
    categoryId: "indo-chinese",
    description: "Fried rice with vegetables, spring onions and Chinese-style seasoning.",
    price: 130,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "10 min",
    rating: 4.7,
    ingredients: ["Basmati Rice", "French Beans", "Carrots", "Sweet Corn", "Spring Onions", "Sesame Oil"],
    imageUrl: "/dishes/veg_fried_rice.jpg",
    imagePrompt: "Ultra-realistic Indo-Chinese Veg Fried Rice, separate fluffy long grains tossed with vibrant finely diced carrots, french beans, and scallions with a hint of smoky wok aroma, served in a contemporary ceramic bowl, soft studio lighting, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-35",
    name: "Chilli Paneer",
    category: "Indo-Chinese",
    categoryId: "indo-chinese",
    description: "Crispy paneer cubes tossed with bell peppers, onions and spicy sauce.",
    price: 170,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "12 min",
    rating: 4.9,
    ingredients: ["Crispy Paneer Cubes", "Green Capsicum", "Red Onions", "Schezwan Chili Glaze", "Spring Onions"],
    imageUrl: "/dishes/chilli_paneer.jpg",
    imagePrompt: "Ultra-realistic Indo-Chinese Chilli Paneer, chunky paneer cubes tossed with vibrant red and green bell peppers, caramelized onions and spicy chili garlic soya sauce glaze, garnished with spring onions, served on dark slate, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-36",
    name: "Veg Spring Rolls",
    category: "Indo-Chinese",
    categoryId: "indo-chinese",
    description: "Crispy rolls filled with seasoned mixed vegetables and served with chili sauce.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.7,
    ingredients: ["Crispy Pastry", "Shredded Cabbage", "Carrots", "Bell Peppers", "Sweet Chili Dip"],
    imageUrl: "/dishes/veg_spring_rolls.jpg",
    imagePrompt: "Ultra-realistic crispy golden Vegetable Spring Rolls, neatly arranged with visible vegetable filling, served with sweet chili sauce in a small bowl, premium Indo-Chinese restaurant presentation, detailed crispy wrapper texture, professional food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 7. FAST FOOD & SNACKS (37 - 42)
  // ==========================================
  {
    id: "item-37",
    name: "Veg Burger",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Vegetarian patty burger with lettuce, tomato, onion and cheese.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.8,
    ingredients: ["Brioche Bun", "Crispy Veg Patty", "Cheddar Cheese", "Lettuce", "Tomato", "House Mayo"],
    imageUrl: "/dishes/veg_burger.jpg",
    imagePrompt: "Ultra-realistic premium vegetarian burger, toasted sesame bun containing crispy vegetable patty, fresh lettuce, tomato, onion and melted cheese, golden French fries on side, modern cafe restaurant presentation, realistic ingredients and textures, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-38",
    name: "Veg Pizza",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Cheese pizza topped with capsicum, onion, sweet corn, tomato and olives.",
    price: 180,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.9,
    ingredients: ["Sourdough Crust", "Herbed Tomato Sauce", "Mozzarella Cheese", "Capsicum", "Sweet Corn", "Olives"],
    imageUrl: "/dishes/veg_pizza.jpg",
    imagePrompt: "Ultra-realistic artisanal Veg Supreme Pizza, fresh oven-baked crispy crust covered in melted bubbling mozzarella cheese, topped with colorful bell peppers, juicy sweet corn kernels, diced tomatoes, red onions, and sliced black olives on a wooden pizza peel, soft studio lighting, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-39",
    name: "French Fries",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Crispy golden potato fries served with ketchup.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "8 min",
    rating: 4.7,
    ingredients: ["Potatoes", "Sea Salt", "Crispy Fried", "Tomato Ketchup"],
    imageUrl: "/dishes/french_fries.jpg",
    imagePrompt: "Ultra-realistic French Fries, crispy golden thin-cut potato fries overflowing in a metal basket with a small glass bowl of tomato ketchup, salt crystals, restaurant food photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-40",
    name: "Paneer Sandwich",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Grilled sandwich filled with paneer, vegetables and cheese.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 4.8,
    ingredients: ["Bread", "Spiced Paneer", "Cheese", "Mint Chutney", "Capsicum & Onions"],
    imageUrl: "/dishes/paneer_sandwich.jpg",
    imagePrompt: "Ultra-realistic grilled Paneer Sandwich, toasted bread filled with grilled paneer, colorful bell peppers, tomato, onion and melted cheese, cut diagonally, served with fries and ketchup, premium cafe presentation, realistic grilled texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-41",
    name: "Samosa",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Crispy Indian pastry filled with spiced potato and peas, served with chutney.",
    price: 60,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.9,
    ingredients: ["Pastry Crust", "Spiced Potatoes", "Green Peas", "Tamarind Chutney", "Mint Chutney"],
    imageUrl: "/dishes/samosa.jpg",
    imagePrompt: "Ultra-realistic classic Indian Samosas, two crisp golden pastry cones filled with spiced potatoes and green peas, served with sweet tamarind chutney and spicy mint chutney, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-42",
    name: "Pav Bhaji",
    category: "Fast Food & Snacks",
    categoryId: "fast-food",
    description: "Spicy mashed vegetable curry served with buttered pav.",
    price: 120,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10 min",
    rating: 5.0,
    ingredients: ["Mashed Mixed Vegetables", "Pav Bhaji Masala", "Amul Butter", "Buttered Pav", "Chopped Onions", "Lemon"],
    imageUrl: "/dishes/pav_bhaji.jpg",
    imagePrompt: "Ultra-realistic legendary Mumbai Pav Bhaji, rich spicy red-orange mashed vegetable curry topped with a huge melting block of butter and fresh chopped coriander, served with golden butter-toasted pav buns, diced onions and lime wedges in steel platter, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 8. DESSERTS (43 - 48)
  // ==========================================
  {
    id: "item-43",
    name: "Gulab Jamun",
    category: "Desserts",
    categoryId: "desserts",
    description: "Soft warm milk-solid dumplings soaked in sweet sugar syrup.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 5.0,
    ingredients: ["Khoya (Mawa)", "Cardamom Sugar Syrup", "Rose Water", "Pistachio Slivers", "Saffron"],
    imageUrl: "/dishes/gulab_jamun.jpg",
    imagePrompt: "Ultra-realistic Indian Gulab Jamun, three soft round golden-brown gulab jamuns soaked in glossy sugar syrup, garnished with pistachio and saffron, served in an elegant dark bowl, premium dessert photography, realistic syrup texture, warm studio lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-44",
    name: "Rasmalai",
    category: "Desserts",
    categoryId: "desserts",
    description: "Soft cheese dumplings soaked in creamy saffron milk and garnished with nuts.",
    price: 110,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 5.0,
    ingredients: ["Chenna Patties", "Thick Saffron Milk (Rabdi)", "Cardamom", "Almonds", "Pistachios"],
    imageUrl: "/dishes/rasmalai.jpg",
    imagePrompt: "Ultra-realistic traditional Rasmalai, soft white chenna dumplings soaked in thick creamy saffron milk, topped with pistachios, almonds and saffron strands, elegant Indian dessert presentation, realistic creamy texture, premium restaurant photography, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-45",
    name: "Gajar Halwa",
    category: "Desserts",
    categoryId: "desserts",
    description: "Traditional carrot dessert cooked with milk and khoya, topped with nuts.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "6 min",
    rating: 4.9,
    ingredients: ["Grated Red Carrots", "Desi Ghee", "Whole Milk", "Mawa (Khoya)", "Cardamom", "Cashews & Almonds"],
    imageUrl: "/dishes/gajar_halwa.jpg",
    imagePrompt: "Ultra-realistic traditional Indian Gajar Halwa, rich orange carrot halwa cooked with milk and khoya, garnished with sliced almonds, pistachios and saffron, served warm in an elegant bowl, premium Indian dessert photography, realistic texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-46",
    name: "Malai Kulfi",
    category: "Desserts",
    categoryId: "desserts",
    description: "Creamy traditional Indian frozen dessert flavored with milk and saffron.",
    price: 90,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "4 min",
    rating: 4.8,
    ingredients: ["Slow-reduced Milk", "Saffron (Kesar)", "Cardamom (Elaichi)", "Crushed Pistachios"],
    imageUrl: "/dishes/malai_kulfi.jpg",
    imagePrompt: "Ultra-realistic traditional Indian Malai Kulfi, creamy cylindrical kulfi pieces on elegant serving plate, garnished with pistachios, almonds and saffron, rich frozen texture, premium Indian dessert restaurant presentation, realistic photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-47",
    name: "Jalebi",
    category: "Desserts",
    categoryId: "desserts",
    description: "Crispy orange spiral sweet soaked in sugar syrup.",
    price: 80,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.8,
    ingredients: ["Fermented Batter", "Ghee Fried", "Saffron Cardamom Sugar Syrup"],
    imageUrl: "/dishes/jalebi.jpg",
    imagePrompt: "Ultra-realistic Indian Jalebi, bright orange crispy spiral jalebi pieces coated with glossy sugar syrup, served warm on an elegant traditional plate, pistachio garnish, authentic Indian dessert photography, highly detailed crispy texture, warm lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-48",
    name: "Shrikhand",
    category: "Desserts",
    categoryId: "desserts",
    description: "Thick sweetened strained yogurt flavored with saffron and cardamom.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "4 min",
    rating: 4.9,
    ingredients: ["Strained Yogurt (Chakka)", "Sugar", "Saffron", "Cardamom", "Pistachios & Charoli"],
    imageUrl: "/dishes/shrikhand.jpg",
    imagePrompt: "Ultra-realistic Maharashtrian and Gujarati Shrikhand, thick creamy sweetened yogurt flavored with saffron and cardamom, topped with pistachios, almonds and saffron strands, served in elegant ceramic bowl, premium Indian dessert photography, realistic creamy texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 9. BEVERAGES (49 - 54)
  // ==========================================
  {
    id: "item-49",
    name: "Masala Chai",
    category: "Beverages",
    categoryId: "beverages",
    description: "Hot Indian tea flavored with aromatic spices.",
    price: 50,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 5.0,
    ingredients: ["Assam Tea Leaves", "Fresh Milk", "Ginger", "Cardamom", "Cinnamon", "Cloves"],
    imageUrl: "/dishes/masala_chai.jpg",
    imagePrompt: "Ultra-realistic Indian Masala Chai, steaming hot spiced tea served in a traditional glass cup, cinnamon, cardamom, cloves and ginger subtly arranged beside the cup, premium cafe presentation, warm cozy lighting, realistic steam and liquid texture, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-50",
    name: "Cold Coffee",
    category: "Beverages",
    categoryId: "beverages",
    description: "Chilled creamy coffee served in a tall glass.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.8,
    ingredients: ["Espresso Coffee", "Chilled Milk", "Ice Cream", "Chocolate Sauce", "Cocoa Powder"],
    imageUrl: "/dishes/cold_coffee.jpg",
    imagePrompt: "Ultra-realistic creamy Indian Cold Coffee served in a tall transparent glass, rich coffee foam on top, chocolate drizzle and coffee beans beside glass, premium modern cafe presentation, condensation on glass, realistic beverage photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-51",
    name: "Mango Lassi",
    category: "Beverages",
    categoryId: "beverages",
    description: "Thick creamy mango yogurt drink garnished with saffron and pistachio.",
    price: 100,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 5.0,
    ingredients: ["Alphonso Mango Pulp", "Curd", "Sugar", "Cardamom", "Saffron", "Pistachios"],
    imageUrl: "/dishes/mango_lassi.jpg",
    imagePrompt: "Ultra-realistic authentic Mango Lassi, thick creamy golden mango yogurt drink served in a traditional clay kulhad, garnished with saffron strands and slivered pistachios, soft natural lighting, 8K UHD, 1:1 square composition, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-52",
    name: "Sweet Lassi",
    category: "Beverages",
    categoryId: "beverages",
    description: "Traditional Punjabi sweet yogurt drink served chilled.",
    price: 80,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "5 min",
    rating: 4.8,
    ingredients: ["Thick Yogurt", "Rose Water", "Sugar", "Malai Cream", "Cardamom", "Pistachios"],
    imageUrl: "/dishes/sweet_lassi.jpg",
    imagePrompt: "Ultra-realistic Punjabi Sweet Lassi, thick creamy frothy yogurt drink served in a traditional tall glass, pistachio and saffron garnish, subtle condensation, premium Indian restaurant presentation, natural soft lighting, realistic creamy texture, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-53",
    name: "Fresh Lime Soda",
    category: "Beverages",
    categoryId: "beverages",
    description: "Refreshing lemon soda with ice, lemon slices and mint.",
    price: 70,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "4 min",
    rating: 4.7,
    ingredients: ["Lime Juice", "Soda", "Black Salt", "Sugar Syrup", "Ice", "Mint Leaves"],
    imageUrl: "/dishes/fresh_lime_soda.jpg",
    imagePrompt: "Ultra-realistic refreshing Fresh Lime Soda, transparent glass filled with sparkling soda, ice cubes, fresh lime slices and mint leaves, visible bubbles and condensation, premium Indian cafe presentation, clean bright background, realistic beverage photography, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-54",
    name: "Masala Buttermilk",
    category: "Beverages",
    categoryId: "beverages",
    description: "Chilled spiced Indian buttermilk with coriander and cumin.",
    price: 60,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: false,
    prepTime: "4 min",
    rating: 4.8,
    ingredients: ["Churned Yogurt (Chaas)", "Roasted Cumin", "Black Salt", "Ginger", "Green Chili", "Coriander", "Mint"],
    imageUrl: "/dishes/masala_buttermilk.jpg",
    imagePrompt: "Ultra-realistic Indian Masala Buttermilk, chilled creamy white buttermilk served in an elegant glass, garnished with coriander, roasted cumin and mint, ice cubes and subtle condensation, premium restaurant beverage photography, 8K UHD, 1:1 square, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },

  // ==========================================
  // 10. ⭐ SPECIAL THALIS (55 - 59)
  // ==========================================
  {
    id: "item-55",
    name: "Maharashtrian Special Thali",
    category: "⭐ Special Thalis",
    categoryId: "special-thalis",
    description: "Includes Puran Poli, Bhakri, Bharli Vangi, Dal, Rice, Kothimbir Vadi, Salad, Chutney and Sweet.",
    price: 249,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15-20 min",
    rating: 5.0,
    ingredients: ["Puran Poli", "Jowar/Bajra Bhakri", "Bharli Vangi", "Varan Bhaat", "Kothimbir Vadi", "Koshimbir Salad", "Thecha/Chutney", "Shrikhand/Sweet"],
    imageUrl: "/dishes/maharashtrian_special_thali.jpg",
    imagePrompt: "Ultra-realistic authentic Maharashtrian Special Thali, traditional stainless steel plate with small katoris containing Bharli Vangi, Dal, Steamed Rice, Puran Poli, Bhakri, crispy Kothimbir Vadi, salad, chutney and sweet, traditional restaurant presentation, realistic food texture, warm studio lighting, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-56",
    name: "Punjabi Special Thali",
    category: "⭐ Special Thalis",
    categoryId: "special-thalis",
    description: "Includes Paneer Butter Masala, Dal Makhani, Jeera Rice, Butter Naan, Raita, Salad and Gulab Jamun.",
    price: 299,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15-20 min",
    rating: 5.0,
    ingredients: ["Paneer Butter Masala", "Dal Makhani", "Jeera Rice", "Butter Naan", "Boondi Raita", "Onion Salad", "Gulab Jamun", "Pickle & Papad"],
    imageUrl: "/dishes/punjabi_special_thali.jpg",
    imagePrompt: "Ultra-realistic authentic Punjabi Special Thali, traditional stainless steel royal platter containing rich Paneer Butter Masala, slow-cooked Dal Makhani, fragrant Jeera Rice, freshly baked Butter Naan, creamy Boondi Raita, crisp onion salad and warm Gulab Jamun in individual bowls, restaurant presentation, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-57",
    name: "South Indian Special Thali",
    category: "⭐ Special Thalis",
    categoryId: "special-thalis",
    description: "Includes Idli, Medu Vada, Sambar, Coconut Chutney, Rice, Rasam, Curd and Sweet.",
    price: 249,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "15 min",
    rating: 4.9,
    ingredients: ["Steamed Idli", "Crispy Medu Vada", "Aromatic Sambar", "Fresh Coconut Chutney", "Steamed Ponni Rice", "Tangy Rasam", "Fresh Curd", "Payasam/Sweet", "Appalam Papad"],
    imageUrl: "/dishes/south_indian_special_thali.jpg",
    imagePrompt: "Ultra-realistic authentic South Indian Special Thali, served on fresh green banana leaf platter with soft Idli, crispy Medu Vada, aromatic Sambar, Coconut Chutney, hot Steamed Rice, Rasam, fresh curd, and Payasam sweet in stainless steel katoris, realistic food photography, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-58",
    name: "Deluxe Veg Thali",
    category: "⭐ Special Thalis",
    categoryId: "special-thalis",
    description: "Includes Paneer Butter Masala, Mix Vegetable Curry, Dal, Jeera Rice, Naan, Vegetarian Starter, Raita, Salad and Dessert.",
    price: 349,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "18-22 min",
    rating: 5.0,
    ingredients: ["Paneer Butter Masala", "Mix Vegetable Curry", "Yellow Dal Tadka", "Jeera Rice", "Butter Naan & Roti", "Crispy Veg Starter", "Mix Veg Raita", "Green Salad", "Gulab Jamun / Rasmalai"],
    imageUrl: "/dishes/deluxe_veg_thali.jpg",
    imagePrompt: "Ultra-realistic Grand Deluxe Vegetarian Thali, lavish royal Indian restaurant platter loaded with multiple curries including Shahi Paneer, Mix Veg, Dal Tadka, Jeera Rice, Tandoori Naan, vegetable kebab starter, raita, salad, roasted papad and rich Indian dessert, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  },
  {
    id: "item-59",
    name: "Mini Veg Thali",
    category: "⭐ Special Thalis",
    categoryId: "special-thalis",
    description: "Includes Dal, Seasonal Vegetable, Rice, 2 Roti, Salad, Pickle and Sweet.",
    price: 179,
    vegetarian: true,
    isVeg: true,
    available: true,
    popular: true,
    prepTime: "10-12 min",
    rating: 4.8,
    ingredients: ["Home-style Dal Fry", "Seasonal Vegetable Sabzi", "Steamed Basmati Rice", "2 Fresh Phulka Rotis with Ghee", "Fresh Cucumber Tomato Salad", "Mango Pickle", "Sweet Gulab Jamun"],
    imageUrl: "/dishes/mini_veg_thali.jpg",
    imagePrompt: "Ultra-realistic authentic Indian Mini Veg Thali, neat compartment steel plate containing golden Dal Fry, seasonal vegetable sabzi, steamed white rice, two hot ghee rotis, fresh salad, spicy pickle and a sweet dumpling, realistic executive lunch presentation, 8K UHD, 1:1, no people, no hands, no text, no logo, no watermark.",
    createdAt: new Date().toISOString()
  }
];

export const DEMO_TABLES = [
  { id: "table-1", tableNumber: "01", capacity: 2, active: true, location: "Window Side", qrUrl: "https://smartdine.netlify.app/menu?table=01", deepLink: "smartdine://table/01" },
  { id: "table-2", tableNumber: "02", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=02", deepLink: "smartdine://table/02" },
  { id: "table-3", tableNumber: "03", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=03", deepLink: "smartdine://table/03" },
  { id: "table-4", tableNumber: "04", capacity: 6, active: true, location: "Family Booth", qrUrl: "https://smartdine.netlify.app/menu?table=04", deepLink: "smartdine://table/04" },
  { id: "table-5", tableNumber: "05", capacity: 2, active: true, location: "Terrace Balcony", qrUrl: "https://smartdine.netlify.app/menu?table=05", deepLink: "smartdine://table/05" },
  { id: "table-6", tableNumber: "06", capacity: 4, active: true, location: "Terrace Balcony", qrUrl: "https://smartdine.netlify.app/menu?table=06", deepLink: "smartdine://table/06" },
  { id: "table-7", tableNumber: "07", capacity: 8, active: true, location: "VIP Lounge", qrUrl: "https://smartdine.netlify.app/menu?table=07", deepLink: "smartdine://table/07" },
  { id: "table-8", tableNumber: "08", capacity: 4, active: true, location: "Main Hall", qrUrl: "https://smartdine.netlify.app/menu?table=08", deepLink: "smartdine://table/08" },
  { id: "table-9", tableNumber: "09", capacity: 2, active: true, location: "Garden Courtyard", qrUrl: "https://smartdine.netlify.app/menu?table=09", deepLink: "smartdine://table/09" },
  { id: "table-10", tableNumber: "10", capacity: 6, active: true, location: "Garden Courtyard", qrUrl: "https://smartdine.netlify.app/menu?table=10", deepLink: "smartdine://table/10" }
];

export const DEMO_ORDERS = [
  {
    id: "ORD-9821",
    tableNumber: "02",
    customerName: "Rahul Sharma",
    customerPhone: "+91 98765 43210",
    customerId: "cust-1",
    items: [
      { itemId: "item-1", name: "Misal Pav", price: 120, quantity: 2, isVeg: true },
      { itemId: "item-51", name: "Mango Lassi", price: 100, quantity: 2, isVeg: true }
    ],
    subtotal: 440,
    tax: 22,
    total: 462,
    status: "preparing",
    paymentStatus: "paid",
    paymentMethod: "UPI / Counter",
    notes: "Please make the rassa spicy and extra lemon",
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString()
  },
  {
    id: "ORD-9822",
    tableNumber: "05",
    customerName: "Priya Nair",
    customerPhone: "+91 91234 56789",
    customerId: "cust-2",
    items: [
      { itemId: "item-7", name: "Masala Dosa", price: 120, quantity: 2, isVeg: true },
      { itemId: "item-49", name: "Masala Chai", price: 50, quantity: 2, isVeg: true }
    ],
    subtotal: 340,
    tax: 17,
    total: 357,
    status: "accepted",
    paymentStatus: "pending",
    paymentMethod: "Pay after Dining",
    notes: "Crispy dosas with hot sambar please",
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString()
  }
];
